/*
 * Sitemap filename patterns from: https://github.com/Abromeit/sitemap-finder
 *
 * Original project is licensed under MIT License:
 * Copyright (c) 2019 Abromeit
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 */

#include "bruteforce_finder.hpp"

namespace duckdb {

std::vector<std::string> BruteforceFinder::GetFiletypes() {
	return {
		"xml",
		"xml.gz",
		"txt"
	};
}

std::vector<std::string> BruteforceFinder::GetFilenames() {
	return {
		"1", "1-1", "1_index_sitemap", "1_de_0_sitemap", "1_en_0_sitemap",
		"01", "001", "0001",
		"2020", "2021", "2022", "2023", "2024", "2025",
		"index", "index-files",
		"s_1", "s_01", "s_001", "s_0001", "s-1", "s-01", "s-001", "s-0001", "s_1-1",
		"s1", "s01", "s001", "s0001", "s1-1",
		"site_1", "site_01", "site_001", "site_0001", "site-1", "site-01", "site-001", "site-0001", "site-1-1",
		"site", "site1", "site01", "site001", "site0001",
		"sites", "siteindex", "siteindex1", "siteindex01", "siteindex001", "siteindex0001",
		"site-map", "site_map", "sitemap", "sitemapmain", "sitemapMain",
		"sitemap.all", "sitemap.index", "sitemap-index.sitemap", "sitemap.website",
		"sitemap-shop", "sitemap.pages", "sitemap.default", "sitemap.main",
		"sitemap.ssl", "sitemap.root", "sitemap.de", "sitemap.en",
		"sitemap.1", "sitemap.01", "sitemap.001", "sitemap.0001",
		"sitemap_0", "sitemap_1", "sitemap_01", "sitemap_001", "sitemap_0001",
		"sitemap_1_1", "sitemap_01_01",
		"sitemap_content", "sitemap_default", "sitemap_en", "sitemap_de",
		"sitemap_index_de", "sitemap_index_en", "sitemap_index",
		"sitemap_sites", "sitemap_ssl",
		"sitemap-1", "sitemap-1-1", "sitemap-01", "sitemap-001", "sitemap-0001",
		"sitemap_hreflang", "sitemapindex", "sitemap-index", "index-sitemap",
		"sitemap-index-1", "sitemap-index-de", "sitemap-index-en",
		"sitemap-complete", "sitemap-default", "sitemap-root", "sitemap-root-1",
		"sitemap-main", "sitemap-pages", "sitemap-posts", "sitemap-sections",
		"sitemap-sites", "sitemap-ssl",
		"sitemap-de", "sitemap-de-de", "sitemap-de_de", "sitemap-deu",
		"sitemap-en", "sitemap-en-us", "sitemap-en_us", "sitemap-eng",
		"sitemap-web", "sitemap-website", "sitemap-www",
		"sitemap-secure", "sitemap-secure-www", "secure-sitemap",
		"sitemaps", "sitemaps-1-sitemap", "sitemapsindex",
		"Sitemap", "SiteMap",
		"sitemap1", "sitemap2", "sitemap01", "sitemap001", "sitemap0001",
		"sitemap-files", "sitemap-items", "sitemap-items-1",
		"sitemappages", "sitemapproducts", "sitemap-4seo",
		"default", "standard_sitemap", "items", "files", "sm",
		"google-sitemap", "google-sitemap-index", "google-sitemap-1",
		"google_sitemap", "googlesitemap", "google.sitemap",
		"gsitemap", "GSiteMap", "gsiteindex",
		"xml-sitemap", "xml_sitemap", "main-sitemap", "name-ihrer-sitemap",
		"news", "news-sitemap", "news_sitemap", "newssitemap",
		"googleNewsList", "gNewsSiteMap", "googlenews",
		"google-news-sitemap", "google-news-index.sitemap", "googlenews-sitemap",
		"sitemap_gnews", "sitemap-google-news", "sitemap-googlenews",
		"sitemap-news", "sitemap_news", "sitemapnews", "sitemapNews",
		"sitemap-archives", "sitemap_articles", "sitemap-cms", "sitemap-global",
		"sitemap_static", "sitemap_global", "sitemap-home", "sitemap_https",
		"sitemap_xml", "sitemap_xml_de", "sitemap_xml_en",
		"sitemaps-all-pages", "sitemap_neu", "sitemap_new", "sitemap-master-index",
		"List", "list", "website", "web", "wp-sitemap",
		"main", "map", "maps", "global", "geositemap",
		"content", "content_index", "page", "pages",
		"page-sitemap", "post-sitemap", "product-sitemap", "product_index",
		"root-sitemap", "all", "all-sitemaps-xml", "add-sitemap",
		"de", "de.sitemap", "en", "en.sitemap",
		"wpms-sitemap", "seo_sitemap", "toprank-sitemap_index_01-aa",
		"urllist", "xmlsitemap",
		"map/1", "map/index", "map/global", "map/default",
		"map/s_1", "map/s-1", "map/s1", "map/site_1", "map/site-1", "map/site",
		"map/siteindex", "map/site1",
		"map/sitemap_1", "map/sitemap_index_de", "map/sitemap_index", "map/sitemap_sites",
		"map/sitemap-1", "map/sitemap-index", "map/sitemap-sites", "map/sitemap",
		"map/sitemap1", "map/sitemap01", "map/sitemap001", "map/sitemap0001",
		"map/sm", "map/main",
		"sitemap/1", "sitemap/01", "sitemap/001", "sitemap/0001",
		"sitemap/de-sitemap", "sitemap/en-sitemap",
		"sitemap/index", "sitemap/index-files", "sitemap/global", "sitemap/news-sitemap",
		"sitemap/s_1", "sitemap/s-1", "sitemap/s1",
		"sitemap/site_1", "sitemap/site-1", "sitemap/site", "sitemap/siteindex", "sitemap/site1",
		"sitemap/sitemap", "sitemap/sitemap_1", "sitemap/sitemap_01", "sitemap/sitemap_001", "sitemap/sitemap_0001",
		"sitemap/sitemap_index_de", "sitemap/sitemap_index", "sitemap/sitemap_sites",
		"sitemap/sitemap-0", "sitemap/sitemap-1", "sitemap/sitemap-01", "sitemap/sitemap-001", "sitemap/sitemap-0001",
		"sitemap/sitemap-index", "sitemap/sitemap-sections", "sitemap/sitemap-sites",
		"sitemap/sitemap-main", "sitemap/sitemap-de", "sitemap/sitemap_de",
		"sitemap/sitemap-en", "sitemap/sitemap_en", "sitemap/sitemap_news",
		"sitemap/sitemap1", "sitemap/sitemap01", "sitemap/sitemap001", "sitemap/sitemap0001",
		"sitemap/map", "sitemap/map1", "sitemap/map01", "sitemap/map001", "sitemap/map0001",
		"sitemap/main", "sitemap/sitemap_global", "sitemap/sitemapmain",
		"sitemap/default", "sitemap/full", "sitemap/items", "sitemap/root",
		"sitemap/sm", "sitemap/web", "sitemap/pages", "sitemap/page-a",
		"sitemap/files", "sitemap/file-a",
		"sitemap/de/add_sitemap", "sitemap/de/sitemap", "sitemap/en/sitemap",
		"sitemap/google/index",
		"sitemaps/1", "sitemaps/01", "sitemaps/001", "sitemaps/0001",
		"sitemaps/index", "sitemaps/pages", "sitemaps/default", "sitemaps/main",
		"sitemaps/news", "sitemaps/sitemap.news",
		"sitemaps/s_1", "sitemaps/s-1", "sitemaps/s1",
		"sitemaps/site_1", "sitemaps/site-1", "sitemaps/site", "sitemaps/siteindex", "sitemaps/site1",
		"sitemaps/sitemap_1", "sitemaps/sitemap_01", "sitemaps/sitemap_001", "sitemaps/sitemap_0001",
		"sitemaps/sitemap_1_1", "sitemaps/sitemap_index_de", "sitemaps/sitemap_de", "sitemaps/sitemap_en",
		"sitemaps/sitemap_index", "sitemaps/sitemap_sites",
		"sitemaps/sitemap-1", "sitemaps/sitemap-01", "sitemaps/sitemap-001", "sitemaps/sitemap-0001",
		"sitemaps/sitemap-index", "sitemaps/sitemap-sites", "sitemaps/sitemap-main",
		"sitemaps/sitemap", "sitemaps/sitemaps",
		"sitemaps/sitemap1", "sitemaps/sitemap01", "sitemaps/sitemap001", "sitemaps/sitemap0001",
		"sitemaps/sitemappages", "sitemaps/sm",
		"sitemaps/de/sitemap", "sitemaps/en/sitemap",
		"sitemaps2/index", "sitemaps-2/index",
		"sitemap_xml/sitemap", "sitemapxml/sitemap",
		"sitemapxmllist/1", "sitemapxmllist/index",
		"sitemapxmllist/s_1", "sitemapxmllist/s-1", "sitemapxmllist/s1",
		"sitemapxmllist/site_1", "sitemapxmllist/site-1", "sitemapxmllist/site",
		"sitemapxmllist/siteindex", "sitemapxmllist/site1",
		"sitemapxmllist/sitemap_1", "sitemapxmllist/sitemap_index_de", "sitemapxmllist/sitemap_index",
		"sitemapxmllist/sitemap_sites", "sitemapxmllist/sitemap-1", "sitemapxmllist/sitemap-index",
		"sitemapxmllist/sitemap-sites", "sitemapxmllist/Sitemap", "sitemapxmllist/sitemap",
		"sitemapxmllist/sitemap1", "sitemapxmllist/sitemap01", "sitemapxmllist/sitemap001", "sitemapxmllist/sitemap0001",
		"sitemapxmllist/sm", "sitemapxmllist-var/index",
		"s/sitemap.xml",
		"sm/1", "sm/index", "sm/s_1", "sm/s-1", "sm/s1",
		"sm/site_1", "sm/site-1", "sm/site", "sm/siteindex", "sm/site1",
		"sm/sitemap_1", "sm/sitemap_index_de", "sm/sitemap_index", "sm/sitemap_sites",
		"sm/sitemap-1", "sm/sitemap-index", "sm/sitemap-sites",
		"sm/Sitemap", "sm/sitemap", "sm/sitemap1", "sm/sitemap01", "sm/sitemap001", "sm/sitemap0001",
		"sm/sm",
		"xml/1", "xml/index", "xml/s_1", "xml/s-1", "xml/s1",
		"xml/site_1", "xml/site-1", "xml/site", "xml/siteindex", "xml/site1",
		"xml/sitemap_1", "xml/sitemap_index_de", "xml/sitemap_index", "xml/sitemap_sites",
		"xml/sitemap-1", "xml/sitemap-index", "xml/sitemap-sites", "xml/sitemap-pages",
		"xml/sitemappages", "xml/Sitemap", "xml/sitemap",
		"xml/sitemap1", "xml/sitemap01", "xml/sitemap001", "xml/sitemap0001",
		"xml/sm", "xml/main", "xml/sitemapmain.xml", "xml/SitemapMain.xml",
		"xml-sitemap/xml-sitemap",
		"export/sitemap", "export/sitemap_0", "export/sitemap_index",
		"export/google_sitemap_de", "export/google_sitemap_en",
		"export/sitemapindex_de",
		"files/sitemap", "files/sitemap-index", "files/sitemap_index",
		"files/sitemap/sitemap", "files/sitemap/sitemap-index", "files/sitemap/sitemap_index",
		"files/sitemap/index",
		"files/sitemaps/sitemap-de", "files/sitemaps/sitemap-en",
		"files/xml/sitemap-index", "files/xml/sitemap", "files/xml/sitemap.pages",
		"files/others/sitemap",
		"sites/default/files/sitemap", "sites/default/files/sitemap/1",
		"sites/default/files/sitemap/sitemap", "sites/default/files/sitemap/sitemap_1",
		"sites/default/files/sitemaps", "sites/default/files/sitemaps/sitemap",
		"sites/default/files/sitemaps/sitemapindex", "sites/default/files/sitemaps/sitemap-index",
		"sites/default/files/sitemaps/sitemap_index", "sites/default/files/sitemaps/sitemapmonthly-1",
		"de/main", "de/sitemap-content", "de/sitemap-de", "de/sitemap_index", "de/sitemap",
		"de/sitemaps-1-sitemap", "de/sitemaps/index", "de/wp-sitemap", "de/googlesitemap",
		"de-de/main", "de-de/sitemap",
		"en/main", "en/sitemap-content", "en/sitemap-en", "en/sitemap_index", "en/sitemap",
		"en/sitemaps-1-sitemap", "en/sitemaps/index", "en/wp-sitemap", "en/googlesitemap",
		"en-us/main", "en-us/sitemap",
		"share/sitemap", "share/sitemap-de", "share/sitemap_de", "share/sitemap-en", "share/sitemap_en",
		"share/sitemap-xml",
		"public/sitemap", "public/sitemap-main", "public/sitemap-de", "public/sitemap-en",
		"public/sitemap-1", "public/sitemap-01", "public/sitemap-001", "public/sitemap-0001",
		"public/sitemap_index", "public/sitemap/index",
		"public/sitemap/de/siteindex", "public/sitemap/en/siteindex",
		"public/sitemap-xml/sitemap",
		"pub/sitemap", "pub/sitemap-1", "pub/sitemap-01", "pub/sitemap-001", "pub/sitemap-0001",
		"pub/sitemap-1-1", "pub/sitemap_de", "pub/sitemap_en",
		"pub/sitemap/sitemap", "pub/sitemaps/sitemap",
		"pub/media/sitemap", "pub/media/sitemap-1-1", "pub/media/sitemap/sitemap",
		"updated/sitemap_index",
		"items/sitemap", "cms/sitemap", "cms/sitemap_index",
		"myinterfaces/cms/googlesitemap-overview",
		"blog/post-sitemap", "blog/sitemap", "blog/sitemap_index", "blog/page-sitemap",
		"wp/sitemap", "wordpress/sitemap",
		"fileadmin/sitemap/sitemap",
		"typo3temp/dd_googlesitemap/sitemap", "typo3temp/sitemap_seiten",
		"temp/sitemap", "temp/sitemap-https",
		"userdata/sitemap", "incms_files/sitemap",
		"navigation/ws/xmlsitemap/sitemap", "nav-sitemap/sitemap_index",
		"site/sitemap", "static/sitemap", "system/sitemap",
		"media/sitemap", "media/sitemap_de", "media/sitemap_en", "media/sitemap/sitemap",
		"docs/sitemap", "seo/sitemap",
		"full", "rss", "rss2", "atom", "feed", "feed/google_sitemap.xml",
		"feeds/sitemap", "datafeed/sitemap-search-de"
	};
}

} // namespace duckdb
